[Application]
SelectedProfile = "gocqhttp"
Daddy = 10001

[[Clients]]
Name = "gocqhttp"
ClientTypeDefined = "Ac682.Hyperai.Clients.CQHTTP.CQClient,Ac682.Hyperai.Clients.CQHTTP"
OptionsTypeDefined = "Ac682.Hyperai.Clients.CQHTTP.CQClientOptions,Ac682.Hyperai.Clients.CQHTTP"
[Clients.Options]
HttpPort = 6259
WebSocketPort = 6260
Host = "HOST"
AccessToken = "ACCESS_TOKEN"
